apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-ingress
  namespace: sandbox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1	
spec:
  rules:
    - http:
        paths:
          - path: /rabbitmq-dashboard
            pathType: Prefix
            backend:
              service:
                name: rabbit-mq-service
                port:
                  number: 15672
          - path: /rabbitmq-amqp
            pathType: Prefix
            backend:
              service:
                name: rabbit-mq-service
                port:
                  number: 5672
#          - path: /message-management-service
#            pathType: Prefix
#            backend:
#              service:
#                name: message-mgmt-service
#                port:
#                  number: 8089
