apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-ingress
  namespace: sandbox
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /message-management-service
            pathType: Prefix
            backend:
              service:
                name: sandbox-message-management-service
                port:
                  number: 8081
